# Generated by Django 3.1.7 on 2022-08-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='显示在下方', max_length=512, null=True, verbose_name='bug标题')),
                ('third_id', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='第三方id')),
                ('iteration', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='迭代版本')),
                ('Severity', models.CharField(choices=[('1', '致命'), ('2', '严重'), ('3', '一般'), ('4', '轻微'), ('5', '建议')], default='', max_length=20)),
                ('priority', models.CharField(choices=[('1', '非常紧急'), ('2', '紧急'), ('3', '一般'), ('4', '不紧急'), ('5', '可缓')], default='', max_length=20)),
                ('bug_type', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='缺陷类型')),
                ('bug_moudle', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='缺陷模块')),
                ('bug_owner', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='缺陷归属人')),
                ('bug_creater', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='缺陷创建人')),
                ('bug_closer', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='缺陷关闭人')),
                ('create_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='创建时间')),
                ('update_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='更新时间')),
                ('finish_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='完成时间')),
                ('status', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='缺陷状态')),
                ('program', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='项目')),
                ('type_owner', models.CharField(blank=True, default='offline', max_length=50, null=True, verbose_name='归属类型')),
            ],
        ),
        migrations.CreateModel(
            name='developdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='开发人员名称')),
                ('iteration_id', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='迭代ID')),
                ('son_program_id', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='子项目ID')),
                ('s_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='开始时间')),
                ('e_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='结束时间')),
                ('reopenBugCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='缺陷reopen个数')),
                ('failedSmokeCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='冒烟测试失败测试')),
                ('delayTestTimes', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='提测延期时间')),
                ('ProgramScores', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='项目主管评分')),
                ('TechScores', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='技术主管评分')),
                ('programScoreDescription', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='项目主管评分说明')),
                ('techScoreDescription', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='技术主管评分说明')),
                ('update_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='iteration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='迭代版本')),
                ('program_id', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='项目ID')),
                ('start_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='迭代开始时间')),
                ('end_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='迭代结束时间')),
                ('create_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='moudle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='perDeveloper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_time', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='本条数据创建时间')),
                ('developer_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='开发者名称')),
                ('scores', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='分数')),
            ],
        ),
        migrations.CreateModel(
            name='perTester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_time', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='本条数据创建时间')),
                ('tester_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='测试者名称')),
                ('scores', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='分数')),
            ],
        ),
        migrations.CreateModel(
            name='program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='项目名称')),
            ],
        ),
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='系数类型')),
                ('rateNum', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='系数数值')),
                ('update_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='son_program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='子项目名称')),
                ('parent_program_id', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='父项目ID')),
                ('online_total_no', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='线上总计')),
                ('offline_total_no', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='线下统计')),
                ('online_resloved_no', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='线上解决数')),
                ('offline_resloved_no', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='线下解决数')),
                ('update_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='testdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='测试人员名称')),
                ('iteration_id', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='迭代ID')),
                ('son_program_id', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='子项目ID')),
                ('s_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='开始时间')),
                ('e_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='结束时间')),
                ('passRunCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='通过用例数')),
                ('failedRunCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='失败用例数')),
                ('blockedRunCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='阻塞用例数')),
                ('notRunCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='未执行用例数')),
                ('offline_BugCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='迭代bug数')),
                ('online_BugCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='线上bug数')),
                ('lost_BugCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='漏测bug数')),
                ('passReviewCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='评审通过用例数')),
                ('failedReviewCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='评审不通过用例数')),
                ('notReviewCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='未评审用例数')),
                ('createdCasesCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='新增用例数')),
                ('ProgramScores', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='项目主管评分')),
                ('TechScores', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='技术主管评分')),
                ('reviewCasesCount', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='新增用例数')),
                ('testDelayTime', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='测试完成延期时间')),
                ('autoFinishRate', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='自动化完成率')),
                ('programScoreDescription', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='项目主管评分说明')),
                ('techScoreDescription', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='技术主管评分说明')),
                ('update_time', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
